"""Typed schema definition for the close-encounter catalog."""

from __future__ import annotations

import polars as pl

CATALOG_SCHEMA: dict[str, type] = {
    "run_id": pl.Utf8,
    "number_1": pl.Int32,
    "number_2": pl.Int32,
    "designation_1": pl.Utf8,
    "designation_2": pl.Utf8,
    "jd_tdb": pl.Float64,
    "date_utc": pl.Utf8,
    "dist_au": pl.Float64,
    "dist_km": pl.Float64,
    "rel_vel_au_day": pl.Float64,
    "rel_vel_km_s": pl.Float64,
    "rel_vel_m_s": pl.Float64,
    "H_1": pl.Float64,
    "H_2": pl.Float64,
    "diameter_1_km": pl.Float64,
    "diameter_2_km": pl.Float64,
    "diameter_source_1": pl.Utf8,
    "diameter_source_2": pl.Utf8,
    "deflection_dv_m_s": pl.Float64,
    "class_1": pl.Utf8,
    "class_2": pl.Utf8,
    "solar_elongation_deg": pl.Float64,
    "solar_elongation_1_deg": pl.Float64,
    "solar_elongation_2_deg": pl.Float64,
    "app_mag_1": pl.Float64,
    "app_mag_2": pl.Float64,
    "gaia_observable_1": pl.Boolean,
    "gaia_observable_2": pl.Boolean,
    "gaia_observable": pl.Boolean,
}

CATALOG_COLUMNS: list[str] = list(CATALOG_SCHEMA.keys())

COLUMN_DESCRIPTIONS: dict[str, str] = {
    "run_id": "Unique identifier for the pipeline run (ISO timestamp)",
    "number_1": "MPC number of asteroid 1 — the larger body (perturber) in the pair after reordering",
    "number_2": "MPC number of asteroid 2 — the smaller body (target) in the pair after reordering",
    "designation_1": "MPC packed designation of asteroid 1 (larger body)",
    "designation_2": "MPC packed designation of asteroid 2 (smaller body)",
    "jd_tdb": "Julian Date of closest approach (TDB scale)",
    "date_utc": "Calendar date of closest approach (UTC, yyyy-mm-dd)",
    "dist_au": "Minimum 3D separation at closest approach (AU)",
    "dist_km": "Minimum 3D separation at closest approach (km)",
    "rel_vel_au_day": "Relative velocity at encounter (AU/day)",
    "rel_vel_km_s": "Relative velocity at encounter (km/s)",
    "rel_vel_m_s": "Relative velocity at encounter (m/s)",
    "H_1": "Absolute magnitude of asteroid 1, V-band, from MPCORB (lower than H_2 by construction except for NaN ties)",
    "H_2": "Absolute magnitude of asteroid 2, V-band, from MPCORB",
    "diameter_1_km": "Diameter of asteroid 1 (km): measured (SBDB) when available, else from H_1 via the albedo priority chain — the larger of the pair",
    "diameter_2_km": "Diameter of asteroid 2 (km): measured (SBDB) when available, else from H_2 via the albedo priority chain",
    "diameter_source_1": "Provenance of diameter_1_km: measured | albedo_measured | zone_albedo | default_albedo | unknown",
    "diameter_source_2": "Provenance of diameter_2_km: measured | albedo_measured | zone_albedo | default_albedo | unknown",
    "deflection_dv_m_s": "Impulse-approximation velocity kick 2GM1/(b·v_rel) on body 2 from body 1 (m/s); GM1 from D1 and a zone-average bulk density — a mass-signal ranking metric, not a measurement",
    "class_1": "Dynamical class of asteroid 1: NEA/MBA/Trojan/Centaur/TNO/Other",
    "class_2": "Dynamical class of asteroid 2: NEA/MBA/Trojan/Centaur/TNO/Other",
    "solar_elongation_deg": "Solar elongation of encounter midpoint from Earth (degrees) — legacy, kept for backwards compatibility",
    "solar_elongation_1_deg": "Solar elongation of asteroid 1 from Earth at encounter (degrees)",
    "solar_elongation_2_deg": "Solar elongation of asteroid 2 from Earth at encounter (degrees)",
    "app_mag_1": "Apparent V magnitude of asteroid 1 at encounter (HG photometric model)",
    "app_mag_2": "Apparent V magnitude of asteroid 2 at encounter (HG photometric model)",
    "gaia_observable_1": "True if asteroid 1 was individually detectable by Gaia at encounter (elongation > 45° AND apparent mag < 21)",
    "gaia_observable_2": "True if asteroid 2 was individually detectable by Gaia at encounter",
    "gaia_observable": "Legacy combined flag: gaia_observable_1 OR gaia_observable_2 — at least one body in the encounter was detectable",
}
